POST http://localhost:5001/scanpal-f74da/us-central1/barizi/auth/register
Content-Type: application/json

{
    "email":"baron@barizicommunications.com",
    "password":"Waru11124"
}

### get user
GET http://localhost:5001/scanpal-f74da/us-central1/barizi/auth/getuser/baron@barizicommunications.com
### add client
POST http://localhost:5001/scanpal-f74da/us-central1/barizi/clients/create
Content-Type: application/json

{
        "company_name": "Asanti consulting",
        "company_email": "admin@belmacconsluting.com",
        "company_phone": "0705122230",
        "address": "2nd Avenue Ngong,I&M Towers"
}
### get all clients
GET http://localhost:5001/scanpal-f74da/us-central1/barizi/clients/get/all
### get single
GET http://localhost:5001/scanpal-f74da/us-central1/barizi/clients/get/sbB7Kzb7236AJBO7uKdc
### update client
PATCH http://localhost:5001/scanpal-f74da/us-central1/barizi/clients/update/sbB7Kzb7236AJBO7uKdc
Content-Type: application/json

{
        "company_name": "Asanti consulting",
        "company_email": "admin@asanticonsulting.com",
        "number_of_employees": 23,
        "company_phone": "0705122230",
        "address": "2nd Avenue Ngong,I&M Towers"
}
### delete client
DELETE http://localhost:5001/scanpal-f74da/us-central1/barizi/clients/delete/73Tzy8ojX6eYIweEcPXy
### add employee
POST http://localhost:5001/scanpal-f74da/us-central1/barizi/people/create/zVD1Ov9ihcmrHZzELgWM
Content-Type: application/json

{
                "bank_name":"equity bank",
                "account_number":"1239499940",
                "accountName":"Warren Ochieng",
                "bank_branch":"KU",       
                "full_name":"Vincent Ochieng",
                "department":"Engineering",
                "designation":"fullstack developer",
                "pay_rate":"300",
                "email":"ochiengwarren10@gmail.com",
                "phone_number":"0605004030",
                "hours_worked":"0",
                "basic_pay":"3000",
                "deductions":[
                    {"name":"NHIF",
                    "value":"4000"},
                    {"name":"NSSF",
                    "value":"4000"}
                ],
                "net_pay":"500"
}

### get all  employees
GET http://localhost:5001/scanpal-f74da/us-central1/barizi/people/get/sbB7Kzb7236AJBO7uKdc

### get single employee
GET http://localhost:5001/scanpal-f74da/us-central1/barizi/people/get/sbB7Kzb7236AJBO7uKdc/single/YTlqFp3XDD0EcfSrknGS

### send test mail
POST http://localhost:5001/scanpal-f74da/us-central1/barizi/mail
### send mpesa
GEt http://127.0.0.1:5001/scanpal-f74da/us-central1/barizi/mpesa/pay/10/254705122230
### test ocr
GET http://127.0.0.1:5001/scanpal-f74da/us-central1/barizi/ocr

